name = "Glogen"
uuid = "e8a80c08-6c9d-43d2-bb6d-a72c511b81d7"
authors = ["Adam Ferreira"]
version = "0.0.1"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
